version: '3'
services:
  gamelog:
    container_name: player
    build:
      context: .
      dockerfile: DOCKERFILE.Dockerfile

    env_file:
      - .env
      
    ports:
      - "8080:8080"
    expose:
      - "8080"
    networks:
      - gameNet
      - mainNet

networks:
  gameNet:
    external: true
  mainNet:
    external: true