server:
  port: 8103
spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_ADDRESS:localhost:29092}
    consumer:
      group-id: generic-player
  endpoints:
    logfile:
      enabled: true
    actuator:
      enabled: true

dungeon:
  mode: "SINGLE" # either "SINGLE" (if you build a player based on this), or "MULTI" (to test the core services)
  singlePlayer:
    playerName: # "Martina Musterfrau" - if undefined, a random name will be chosen
    playerEmail: # "martina@musterfrau.de" - if undefined, a random name will be chosen
  multiPlayer:
    number: 25
  services:
    game: ${GAME_SERVICE}

logging:
  file:
    path: /logs

management:
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    # Don't worry, secrets will be sanitized
    configprops:
      enabled: true
    env:
      enabled: true
    beans:
      enabled: true
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info,health,configprops,env,beans,metrics,logs