server:
  port: 8103
spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_ADDRESS:localhost:29092}
    consumer:
      group-id: player-robocop
      auto-offset-reset: earliest
  web:
    resources:
      static-locations:
        - file:./backend/src/main/resources/public
        - classpath:/static/
        - classpath:/public/
  endpoints:
    logfile:
      enabled: true
    actuator:
      enabled: true
  datasource:
    url: jdbc:h2:file:./backend/db/robocop;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: robocop
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      dialect: org.hibernate.dialect.H2Dialect

dungeon:
  mode: "SINGLE" # either "SINGLE" (if you build a player based on this), or "MULTI" (to test the core services)
  singlePlayer:
    playerName: Robocop
    playerEmail: robocop@cop.cop
  multiPlayer:
    number: 25
  services:
    game: ${GAME_SERVICE}

logging:
  file:
    path: ./backend/logs

management:
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    # Don't worry, secrets will be sanitized
    configprops:
      enabled: true
    env:
      enabled: true
    beans:
      enabled: true
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info,health,configprops,env,beans,metrics,logs
